### ISSUE TITLE
`protocol` kwarg in `get_tags` not working

### ISSUE THREAD

**Issue by Rubikoid** [crashvb/docker-registry-client-async#35]
Passing any `protocol` kwargs to `_get_tags`  makes no sense, because it is not passed to `_get_request_headers`, which leads to exception in `_get_auth_token`, because of resolving from [`DEFAULT_PROTOCOL`](https://github.com/crashvb/docker-registry-client-async/blob/9bcf45b0d90431facfda735aa87c4c553d4b1b5f/docker_registry_client_async/dockerregistryclientasync.py#L225) here.

**Comment by crashvb** [comment]
If I'm following correctly, the issue being reported is that the default value of `DEFAULT_PROTOCOL` (`https`) is not aligned with the passed value of the `protocol` parameter, because it is not exposed via the call stack to the method that populates the auth headers ...?

Without knowing the use case (assuming that `protocol` is being provided to disable TLS, for local testing -- e.g. `http`), it might be easier to override the value of `DockerRegistryClientAsync.DEFAULT_PROTOCOL` directly, which would align the protocols used for any / all invoked methods.

If the scenario is different, such as synchronizing content between two registries of mixed protocols, it would be helpful to better understand the specifics of the protocols involved.

**Comment by Rubikoid** [comment]
> that the default value of `DEFAULT_PROTOCOL` (`https`) is not aligned with the passed value of the protocol parameter, because it is not exposed via the call stack to the method that populates the auth headers

Not exactly. 
The issue is about the `protocol` parameter, which is not passed to method that populates auth headers.

In other words, the only way to populate auth token over http is to change `DockerRegistryClientAsync.DEFAULT_PROTOCOL`, and also it changes only globally, not per client instance.

> assuming that protocol is being provided to disable TLS, for local testing -- e.g. `http`

Yes, exactly. In my case, I need at one time access my local registry over http and also the global docker registry over https.

**Comment by crashvb** [comment]
It's been a while since I worked on this package; had to migrate off docker-compose, update a few tests, and defer some dockerhub changes, but I think I managed to isolate a scenario that gives some confidence that the expose `protocol` parameter is working. Give it a try, let me know if you run into an edge-case.
